---
# application main params
general:
    # where all path and following file are located
    basedirectory: '.'
    # following directories or files a under "basedirectory"
    shared: 'shared'
    neo4j: "data/neo4j"
    mongodb: "localhost"
    processes: 2
# extraction settings
extraction:
    doc_extraction:
        # the following values are some document object attr:
        - 'content'
        - 'label'
    # extraction size
    ngramMin: 2
    ngramMax: 2
    minWordSize: 3
    # under "basedirectory" directory, delete this file to regenerate a new one
    tagger: "tagger.pickle"
    # Reg Expression for NGram extraction
    #postag_valid: '^((VB,|VBD,|VBG,|VBN,|CD.?,|JJ.?,|\?,){0,2}?(N.?,|\?,)+?(CD.,)?)+?((PREP.?|DET.?,|IN.?,|CC.?,|\?,)((VB,|VBD,|VBG,|VBN,|CD.?,|JJ.?,|\?,){0,2}?(N.?,|\?,)+?)+?)*?$'
    postag_valid: '^((VBD,|VBG,|VBN,|JJ.?,|\?,){0,2}?(N.?.?,|\?,)+?)+?((PREP.?|DET.?,|IN.?,|CC.?,|\?,)((VBD,|VBG,|VBN,|JJ.?,|\?,){0,2}?(N.?.?,|\?,)+?)+?)*?$'
