---
# application main params
general:
    # where all path and following file are located
    basedirectory: '.'
    # following directories or files a under "basedirectory"
    shared: 'shared'
    neo4j: "http://localhost:7474/db/data/"
    mongodb: "localhost"
# extraction settings
extraction:
    # stopwords are under share
    stopwords: 'stopwords/en.txt'
    doc_extraction:
        # the following values can be document object fields:
        - 'content'
        - 'label'
    # extraction size
    ngramMin: 1
    ngramMax: 3
    minWordSize: 3
    # under "basedirectory" directory, delete this file to regenerate a new one
    tagger: "conll2000_brill_aubt.pickle"
    # Reg Expression for NGram extraction
    postag_valid: '^((VB,|VBD,|VBG,|VBN,|CD.?,|JJ.?,|\?,){0,2}?(N.?,|\?,)(CD.,)?)+?((PREP.?|DET.?,|IN.?,|CC.?,|\?,)((VB,|VBD,|VBG,|VBN,|CD.?,|JJ.?,|\?,){0,2}?(N.?,|\?,))+?)*?$'
