---
# application main params
general:
    # where all path and following file are located
    loglevel: 'debug'
    basedirectory: '.'
    locale: 'en_US.UTF-8'
    # following directories or files a under "basedirectory"
    user: 'user'
    shared: 'shared'
# extraction settings
extraction:
    userstopwords: 'user_stopwords.csv'
    # stopwords are under share
    stopwords: 'stopwords/en.txt'
    doc_extraction:
        # the following values can be document object fields:
        # - defined by one of the field's value
        # - constants required fields : 'content'/'label'/'id'
        - 'content'
        #- 'label'
    # extraction size
    ngramMin: 1
    ngramMax: 4
    minWordSize: 3
    # tagger learning on 2 x training_tagger_size sentences of tagged nltk corpus
    training_tagger_size: 10000
    # under "basedirectory" directory, delete this file to regenerate a new one
    tagger: "/iscpif/users/showk/nltk_data/taggers/conll2000_brill_aubt.pickle"
    # change this Reg Expression to change NGram extraction filtering
    postag_valid: '^((VB,|VBD,|VBG,|VBN,|CD.?,|JJ.?,|\?,){0,2}?(N.?,|\?,)(CD.,)?)+?((PREP.?|DET.?,|IN.?,|CC.?,|\?,)((VB,|VBD,|VBG,|VBN,|CD.?,|JJ.?,|\?,){0,2}?(N.?,|\?,))+?)*?$'
graph:
    template: 'shared/gexf/gexf.cables_only.template'
    # default values if no params are passed to gexf exporter
    DocumentGraph:
        edgethreshold:
            - 0.0001
            - 'inf'
        nodethreshold:
            - 1.00
            - 'inf'
        #proximity: 'sharedNGrams'
        proximity: 'logJaccard'
    NGramGraph:
        edgethreshold:
            - 0.0001
            - 'inf'
        nodethreshold:
            - 1.00
            - 'inf'
        alpha: 0.10
        #hapax: 1
        proximity: 'Cooccurrences'
        #proximity: 'EquivalenceIndex'
        #proximity: 'PseudoInclusion'
